/*
 * File: app/store/PeopleStore.js
 *
 * This file was generated by Sencha Architect version 3.0.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.PeopleStore', {
    extend: 'Ext.data.Store',

    requires: [
        'MyApp.model.PeopleModel',
        'Ext.util.Grouper',
        'Ext.data.proxy.JsonP',
        'Ext.data.reader.Json',
        'Ext.MessageBox'
    ],

    config: {
        autoSync: true,
        model: 'MyApp.model.PeopleModel',
        storeId: 'PeopleStore',
        grouper: {
            groupFn: function(item) {
                return item.get('lastname')[0];
            }
        },
        proxy: {
            type: 'jsonp',
            reader: {
                type: 'json',
                rootProperty: 'people'
            }
        }
    }
});